/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 paper.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/paper.gltf')
  return (
    <group {...props} dispose={null} onClick={(e) => props.zoomToView(e.object.position)}>
      <group position={[0.15, -0.81, -0.44]} rotation={[-Math.PI / 2, 0, 0]} scale={0.009}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Plane_BackgroundMaterial_0.geometry} material={materials.BackgroundMaterial} position={[0, -5.37, -41.87]} rotation={[-Math.PI / 2, 0, 0]} scale={120.57} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/paper.gltf')
