/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 pcpc.gltf
*/

import React, { useState } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/pcpc.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[0.15, -0.69, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={0.009}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, -5.37, -41.87]} rotation={[-Math.PI / 2, 0, 0]} scale={120.57}>
            <mesh 
              onClick={(e) => props.zoomToView(e.object.position)}
              geometry={nodes.Plane_BackgroundMaterial_0.geometry} 
              material={materials.BackgroundMaterial} 
            />
            <mesh geometry={nodes.Plane_ShadowMaterial_0.geometry} material={materials.ShadowMaterial} />
          </group>
          <mesh geometry={nodes.Comp_Screen000_TerminalMaterial_0.geometry} material={materials.TerminalMaterial} position={[18.16, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={212.25} />
          <mesh geometry={nodes.Comp_Screen002_TerminalMaterial_0.geometry} material={materials.TerminalMaterial} position={[18.16, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={212.25} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/pcpc.gltf')
