/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 pcpc.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/pcpc.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.07, -0.81, -0.44]} rotation={[-Math.PI / 2, 0, 0]} scale={0}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Comp_Screen000_TerminalMaterial_0.geometry} material={materials.TerminalMaterial} position={[18.16, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={212.25} />
          <mesh geometry={nodes.Comp_Screen002_TerminalMaterial_0.geometry} material={materials.TerminalMaterial} position={[18.16, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={212.25} />
          <mesh geometry={nodes.Plane_BackgroundMaterial_0.geometry} material={materials.BackgroundMaterial} position={[0, -5.37, -41.87]} rotation={[-Math.PI / 2, 0, 0]} scale={120.57} />
        </group>
      </group>
      <group position={[-0.07, -0.81, -0.44]} rotation={[-Math.PI / 2, 0, 0]} scale={0}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Plane_BackgroundMaterial_0001.geometry} material={materials['BackgroundMaterial.001']} position={[0, -5.37, -41.87]} rotation={[-Math.PI / 2, 0, 0]} scale={120.57} />
        </group>
      </group>
      <group position={[-0.07, -0.81, -0.44]} rotation={[-Math.PI / 2, 0, 0]} scale={0}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Plane_BackgroundMaterial_0002.geometry} material={materials['BackgroundMaterial.002']} position={[0, -5.37, -41.87]} rotation={[-Math.PI / 2, 0, 0]} scale={120.57} />
        </group>
      </group>
      <group position={[-0.07, -0.81, -0.44]} rotation={[-Math.PI / 2, 0, 0]} scale={0}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Plane_BackgroundMaterial_0003.geometry} material={materials['BackgroundMaterial.003']} position={[0, -5.37, -41.87]} rotation={[-Math.PI / 2, 0, 0]} scale={120.57} />
        </group>
      </group>
      <group position={[-0.07, -0.81, -0.44]} rotation={[-Math.PI / 2, 0, 0]} scale={0}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Plane_BackgroundMaterial_0004.geometry} material={materials['BackgroundMaterial.004']} position={[0, -5.37, -41.87]} rotation={[-Math.PI / 2, 0, 0]} scale={120.57} />
        </group>
      </group>
      <group position={[-0.07, -0.81, -0.44]} rotation={[-Math.PI / 2, 0, 0]} scale={0}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Plane_BackgroundMaterial_0005.geometry} material={materials['BackgroundMaterial.005']} position={[0, -5.37, -41.87]} rotation={[-Math.PI / 2, 0, 0]} scale={120.57} />
        </group>
      </group>
      <group position={[-0.22, 0, 0]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Plane_BackgroundMaterial_0006.geometry} material={materials['BackgroundMaterial.006']} position={[0, -5.37, -41.87]} rotation={[-Math.PI / 2, 0, 0]} scale={120.57} />
      </group>
      <group position={[-0.07, -0.81, -0.44]} rotation={[-Math.PI / 2, 0, 0]} scale={0}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Plane_BackgroundMaterial_0007.geometry} material={materials['BackgroundMaterial.007']} position={[0, -5.37, -41.87]} rotation={[-Math.PI / 2, 0, 0]} scale={120.57} />
        </group>
      </group>
      <group position={[-0.07, -0.81, -0.44]} rotation={[-Math.PI / 2, 0, 0]} scale={0}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Plane_BackgroundMaterial_0008.geometry} material={materials['BackgroundMaterial.008']} position={[0, -5.37, -41.87]} rotation={[-Math.PI / 2, 0, 0]} scale={120.57} />
        </group>
      </group>
      <group position={[-0.07, -0.81, -0.44]} rotation={[-Math.PI / 2, 0, 0]} scale={0}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Plane_BackgroundMaterial_0009.geometry} material={materials['BackgroundMaterial.009']} position={[0, -5.37, -41.87]} rotation={[-Math.PI / 2, 0, 0]} scale={120.57} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/pcpc.gltf')
