/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 room.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/room.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[-3.65, -2.62, 0.31]} rotation={[-Math.PI / 2, 0, 0]} scale={1.47}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[5.67, 2.95, 1.32]} rotation={[0, -Math.PI / 2, 0]} scale={0.01}>
            <group rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
              <group position={[0, 0, 50]} rotation={[0, 0, -Math.PI / 2]}>
                <group position={[-40.11, 0, -50]} rotation={[0, 0, Math.PI / 2]}>
                  <mesh geometry={nodes.A38_Window_120x150_062_Mat_A38_Window_Frame_001_0.geometry} material={materials.Mat_A38_Window_Frame_001} />
                  <mesh geometry={nodes.A38_Window_120x150_062_Mat_A38_Window_Frame_002_0.geometry} material={materials.Mat_A38_Window_Frame_002} />
                  <mesh geometry={nodes.A38_Window_120x150_062_Mat_A38_Window_FrameX_003_0.geometry} material={materials.Mat_A38_Window_FrameX_003} />
                  <mesh geometry={nodes.A38_Window_120x150_062_Mat_A38_Window_Glass_001_0.geometry} material={materials.Kaca} />
                  <mesh geometry={nodes.A38_Window_120x150_062_Mat_A38_Window_Handbar_001_0.geometry} material={materials.Mat_A38_Window_Handbar_001} position={[0, -103.98, 0]} />
                  <mesh geometry={nodes.A38_Window_120x150_062_Mat_A38_Window_Plastic_001_0.geometry} material={materials.Mat_A38_Window_Plastic_001} position={[0, -103.92, 0]} />
                  <mesh geometry={nodes.A38_Window_120x150_062_Mat_A38_Window_Plastic_001_0002.geometry} material={materials.Mat_A38_Window_Plastic_001} position={[0, 107.95, 0]} />
                  <mesh geometry={nodes.A38_Window_120x150_062_Mat_A38_Window_Rubber_001_0.geometry} material={materials.Mat_A38_Window_Rubber_001} />
                  <mesh geometry={nodes.A38_Window_120x150_062_Mat_A38_Window_Wall_001_0.geometry} material={materials.Mat_A38_Window_Wall_001} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
      <group position={[0.52, 1.41, 0.08]} rotation={[-Math.PI / 2, 0, -1.17]} scale={0.01}>
        <mesh geometry={nodes.Object_2.geometry} material={materials['DARK_GREY_MATTE.001']} />
        <mesh geometry={nodes.Object_3.geometry} material={materials['DARK_GREY_MATTE.001']} />
        <mesh geometry={nodes.Object_4.geometry} material={materials['Metal.001']} />
        <mesh geometry={nodes.Object_5.geometry} material={materials['NEON_Green_Light.001']} />
        <mesh geometry={nodes.Object_6.geometry} material={materials['Silver.001']} />
      </group>
      <group position={[-0.12, 1.4, 0.06]} rotation={[-Math.PI / 2, 0, 0]} scale={0.12}>
        <mesh geometry={nodes.Plane001_Material002_0.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Plane001_Material003_0.geometry} material={materials['Material.004']} />
        <mesh geometry={nodes.Plane001_Material004_0.geometry} material={materials['Material.006']} position={[-1.19, 0.09, -0.11]} rotation={[0, 0, -0.26]} />
      </group>
      <group position={[0.11, 1.4, -0.77]} rotation={[Math.PI / 2, 0, 1.58]} scale={0.1}>
        <group position={[2.05, 0, -4.94]} rotation={[0, 0.12, 0]} scale={[0.26, 15.13, 7.46]}>
          <mesh geometry={nodes.Mesh.geometry} material={materials.MAT_Plastic} />
          <mesh geometry={nodes.Mesh_1.geometry} material={materials.MAT_Screen} />
        </group>
        <mesh geometry={nodes.Peana.geometry} material={materials.MAT_Plastic} position={[0.08, 0, 0]} />
      </group>
      <group position={[-3.65, -2.62, 2.47]} rotation={[-Math.PI / 2, 0, 0]} scale={1.47}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[5.67, 2.95, 1.32]} rotation={[0, -Math.PI / 2, 0]} scale={0.01}>
            <group rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
              <group position={[0, 0, 50]} rotation={[0, 0, -Math.PI / 2]}>
                <group position={[-40.11, 0, -50]} rotation={[0, 0, Math.PI / 2]}>
                  <mesh geometry={nodes.A38_Window_120x150_062_Mat_A38_Window_Frame_001_0001.geometry} material={materials['Mat_A38_Window_Frame_001.001']} />
                  <mesh geometry={nodes.A38_Window_120x150_062_Mat_A38_Window_Frame_002_0001.geometry} material={materials['Mat_A38_Window_Frame_002.001']} />
                  <mesh geometry={nodes.A38_Window_120x150_062_Mat_A38_Window_FrameX_003_0001.geometry} material={materials['Mat_A38_Window_FrameX_003.001']} />
                  <mesh geometry={nodes.A38_Window_120x150_062_Mat_A38_Window_Glass_001_0001.geometry} material={materials['Kaca.001']} />
                  <mesh geometry={nodes.A38_Window_120x150_062_Mat_A38_Window_Handbar_001_0001.geometry} material={materials['Mat_A38_Window_Handbar_001.001']} />
                  <mesh geometry={nodes.A38_Window_120x150_062_Mat_A38_Window_Plastic_001_0001.geometry} material={materials['Mat_A38_Window_Plastic_001.001']} />
                  <mesh geometry={nodes.A38_Window_120x150_062_Mat_A38_Window_Rubber_001_0001.geometry} material={materials['Mat_A38_Window_Rubber_001.001']} />
                  <mesh geometry={nodes.A38_Window_120x150_062_Mat_A38_Window_Wall_001_0001.geometry} material={materials['Mat_A38_Window_Wall_001.001']} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
      <mesh geometry={nodes.Desk.geometry} material={materials.Desk_Diffuse} />
      <mesh geometry={nodes.Desk001.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Wall.geometry} material={materials.Wall} position={[-0.07, 3.73, 3.09]} scale={[4.81, 3.73, 4.09]} />
      <mesh geometry={nodes.WCeil.geometry} material={materials.Wall} position={[-0.07, 7.46, 3.09]} scale={[4.81, 1, 4.09]} />
      <mesh geometry={nodes.WWall.geometry} material={materials.Wall} position={[-0.07, 3.73, 7.17]} rotation={[Math.PI / 2, 0, 0]} scale={[4.81, 1, 3.73]} />
    </group>
  )
}

useGLTF.preload('/room.gltf')
