/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 scene-processed.gltf
Author: dylanheyes (https://sketchfab.com/dylanheyes)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/white-modern-living-room-afb8cb0cbee1488caf61471ef14041e9
Title: White Modern Living Room
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/testRoom.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.23}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh geometry={nodes.Structure_Structure_0.geometry} material={materials.Structure} position={[0, 800, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[1174.8, 1076.9, 890]} />
          <mesh onClick={() => {console.log('aaa')}} geometry={nodes.CoffeeTable_CoffeeTable_0.geometry} material={materials.CoffeeTable} position={[-100, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Sofa_Sofa_0.geometry} material={materials.Sofa} position={[-900, -29.16, 847.79]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Lamp_Lamp_0.geometry} material={materials.Lamp} position={[-900, 0, -900]} rotation={[-Math.PI / 2, 0, -Math.PI / 9]} scale={100} />
          <mesh geometry={nodes.TVStand_TVStand_0.geometry} material={materials.TVStand} position={[200, 0, -1075.35]} rotation={[-Math.PI / 2, 0, 0]} scale={[470, 110, 100]} />
          <mesh geometry={nodes.TV_TV_0.geometry} material={materials.material} position={[200, 600, -1094.67]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[-450, 25, 250]} />
          <mesh geometry={nodes.PictureFrame_Material_0.geometry} material={materials.Material} position={[-1216.29, 802.72, 480]} rotation={[-Math.PI / 2, -0.17, 0]} scale={60} />
          <mesh geometry={nodes.AbstractArt_AbstractArt_0.geometry} material={materials.AbstractArt} position={[-1334.38, 660, 10]} rotation={[-Math.PI / 2, 0, 0]} scale={[170, 170, 272]} />
          <mesh geometry={nodes.Plant__0.geometry} material={materials.Plant__0} position={[-1136.27, 634.51, 698.7]} rotation={[-Math.PI / 2, 0, 0]} scale={26.88} />
          <mesh geometry={nodes.Pillows_Pillows_0.geometry} material={materials.Pillows} position={[-806.33, 147.05, 762.71]} rotation={[-Math.PI / 2, 1.4, 0]} scale={[80.68, 100, 99.46]} />
          <mesh geometry={nodes.Windows_Windows_0.geometry} material={materials.Windows} position={[0, 800, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[1174.8, 1076.9, 890]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene-processed.gltf')
