/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 scene-processed.gltf
Author: LamedeFeu (https://sketchfab.com/lamedefeu)
License: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
Source: https://sketchfab.com/3d-models/windmill-game-ready-6a006afce57a447baa60c7a6791f0086
Title: Windmill (game ready)
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/windmill.gltf')
  const { actions, mixer} = useAnimations(animations, group)
  useEffect(() => {
    actions['Windy day'].play();
  }, []);
  
  return (
    <group onClick={() => {actions['Windy day'].play()}} ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="ca383a8524684a959cd40c5276ee2149fbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Object_4">
                  <group name="RING" position={[-0.38, 2.49, 1.44]}>
                    <mesh name="RING_standardSurface1_0" geometry={nodes.RING_standardSurface1_0.geometry} material={materials.standardSurface1} />
                  </group>
                  <primitive object={nodes._rootJoint} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/windmill.gltf')
